spring:
  application:
    name: Document Storage Service
  datasource:
    url: jdbc:h2:file:${storage.directory}/metadata;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7300

storage:
  directory: ./docs